"""empty message

Revision ID: cff21f3b655e
Revises: 71654fcd2bf9
Create Date: 2021-08-21 10:27:15.737693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff21f3b655e'
down_revision = '71654fcd2bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('invitation_text', sa.String(length=500), nullable=True))
    op.drop_constraint('trip_invitation_id_fkey', 'trip', type_='foreignkey')
    op.drop_column('trip', 'invitation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('invitation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('trip_invitation_id_fkey', 'trip', 'invitation_info', ['invitation_id'], ['id'])
    op.drop_column('trip', 'invitation_text')
    # ### end Alembic commands ###
